/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FakeEUR } from "./FakeEUR";
export type { FakeFGZ } from "./FakeFGZ";
export type { FakeUSD } from "./FakeUSD";
export type { TokenDistributor } from "./TokenDistributor";
